/* Collection table tp store POS sale data */
CREATE TABLE IF NOT EXISTS pointofsale (POS JSON);
CREATE TABLE IF NOT EXISTS possync (CUSTOMERMOBILE varchar(15) UNIQUE, TENANTID VARCHAR(50) NOT NULL);
CREATE TABLE IF NOT EXISTS possequence (CURRENTSEQUENCVALUE int, INCREMENTVALUE int DEFAULT 1);

/* initial data load*/
INSERT INTO possequence VALUES (1, 1);